# Generated by Django 4.2.3 on 2023-08-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_key',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
