# Generated by Django 4.2.3 on 2023-08-02 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_user_qr_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='qr_key',
            new_name='qr_code',
        ),
    ]
