# Generated by Django 4.2.3 on 2023-08-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(related_name='participants', to='registration.event'),
        ),
    ]
