# Generated by Django 4.2.3 on 2023-08-02 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_user_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
    ]
