# Generated by Django 4.2.3 on 2023-08-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_remove_user_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(related_name='participants', to='registration.event'),
        ),
    ]
